version: "3"
volumes:
  db:
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=iabot
      - MYSQL_PASSWORD=5yBtFxeedrfupieNk7mp1oWyP8aR91kAp9nO8oSH
      - MYSQL_ROOT_PASSWORD=5yBtFxeedrfupieNk7mp1oWyP8aR91kAp9nO8oSH
    volumes:
      - db:/var/lib/mysql
  iabot:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app/src:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/iabot.ini
      - ./vendor:/vendor
    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.internal
      - MYSQL_DB=iabot
      - MYSQL_USER=root
      - MYSQL_PASSWORD=5yBtFxeedrfupieNk7mp1oWyP8aR91kAp9nO8oSH
      - MYSQL_ROOT_PASSWORD=5yBtFxeedrfupieNk7mp1oWyP8aR91kAp9nO8oSH
    extra_hosts:
      host.docker.internal: host-gateway
